# Copyright (c) 2025 harokku999@gmail.com
# Licensed under the MIT License - https://opensource.org/licenses/MIT

users:
  testme4nx:
    NEXTCLOUD_USERNAME: "testme4nx"
    NEXTCLOUD_PASSWORD: "change-me"